### ISSUE TITLE
Diffusion de phpBB Directory - Annuaire

### ISSUE THREAD

**Issue by Galixte** [ErnadoO/ext-phpbb-directory#17]
Salut ErnadoO,

je viens de voir que tu t’intéressé à la branche 3.2.x de phpBB. Aussi, je me pose les questions suivantes :

Comptes-tu faire valider ton extension pour la branche 3.1.x ?

A t-elle une page officielle sur un autre site Web ?

Bonne continuation !

**Comment by ErnadoO** [comment]
Salut Galixte

Oui je compte bien faire valider cette extension (que ce soit pour la branche 3.1 ou 3.2) mais le hic c'est que je vois toujours quelque chose à corriger/améliorer dans le code, du coup je repousse sans cesse, de peur d'essuyer un refus par .com, comme ce fut le cas avec le mod annuaire pour la branche 3.0: Je pensais le code apte à passer la validation, et au final il m'a fallu proposer 6 versions étalées sur + d'un an pour satisfaire ces messieurs, du coup, cette fois-ci, je prend mon temps, surtout que, comparé aux extensions validées, la mienne est, je crois, la plus complète (controller, notifications, cron, nested tree, etc...) ce qui me donne pas d'elements de comparaisons afin de savoir si ma méthodologie est la bonne.

J'ai créé la branche 3.2.x car je vois passer pas mal de PR interessants pour cette branche qui sont utiles pour mon extension, et j'en ai un paquet à traiter, donc j'intègre ces nouveautées au fil de l'eau.

Et pour terminer, non je n'ai pas de page officielle ;)

**Comment by Galixte** [comment]
Je recense sur ce sujet toutes les extensions que je compte traduire : http://www.ezcom-fr.com/viewtopic.php?f=2&t=279.

Dans cette liste, tu as l’extension Board3 portal qui va être soumise à validation dans les jours qui viennent, et disponible sur cette page : https://github.com/board3/Board3-Portal.

Ensuite, en grosse extension, tu as :
- https://github.com/oxpus/Download-Extention ;
- https://github.com/BoardTools/upload ;
- https://github.com/satanasov/phpbbgallery.

Si cela peut te fournir des éléments de comparaison. ;)

**Comment by Galixte** [comment]
Ah j’oubliais les extensions de https://github.com/Wolfsblvt car comme le développeur satanasov il utilise une extension rien pour le code, donc je me dis que cela pèse un peu plus lourd qu’une simple extension.

Et aussi, ce portail : https://github.com/phpbbireland/phpbb3-extension-portal.

A chaque fois je le vois à l’ampleur des traductions à faire ^_^.

**Comment by ErnadoO** [comment]
Je connais la plupart de ces extensions, mais tant qu'elles ne sont pas validées, je ne peux pas me baser dessus^^

Tu penses avoir assez d'une vie pour traduire toutes ces extensions? :o

**Comment by Galixte** [comment]
J’en ai déjà traduit le tiers, je reste confiant. ;)

**Comment by Galixte** [comment]
Salut @ErnadoO,

je vois que la version 1.0.0 a été publiée il y a bientôt un mois, l’as-tu soumise à validation ? Auquel cas bonne chance. ;)

**Comment by ErnadoO** [comment]
Hello Galixte,

Oui j'ai soumis mon extension à .com le 26 Août, et comme c'est pas une petite extension, je ne m'attend pas à un refus avant encore un bon mois lol

**Comment by Galixte** [comment]
Qui sait ? Une validation à la clé du premier ça existe aussi. Je me rappelle lorsque Ptirhiik soumettait son MOD Categories Hierarchy, c’était validé d’office. ^_^

**Comment by ErnadoO** [comment]
C'est possible lorsque tu t'appelles Ptirhiik, ou en proposant une extension"Hello world" :p

**Comment by ErnadoO** [comment]
Et bien qui l'eu cru, mon extension a été validée dès le 1er coup: https://www.phpbb.com/customise/db/extension/phpbb_directory/
:)

**Comment by Galixte** [comment]
Bravo à toi je viens de voir ça, champion !-)
