### ISSUE TITLE
Compatibilité avec l’extension ABBC3

### ISSUE THREAD

**Issue by Galixte** [ErnadoO/ext-phpbb-directory#19]
Salut @ErnadoO,

tu peux jeter un œil pour que la fenêtre popup des commentaires affiche correctement les boutons des BBCodes de cette extension : https://github.com/Galixte/abbc3 ?

**Comment by ErnadoO** [comment]
Salut Galixte

Un membre sur .com m'a remonté ce petit soucis,je lui donne la solution là bas: https://www.phpbb.com/community/viewtopic.php?p=13965811#p13965811

Au final je ne peux fien faire de mon côté :/

**Comment by Galixte** [comment]
L’auteur de l’extension Ajax Chat a réussi en faisant ceci : https://github.com/LMOspaceace/ajaxchat/commit/8b034c5eca8876caf78a3637cd07cd4a93873d7a.

Il semble que son fichier : https://github.com/LMOspaceace/ajaxchat/blob/8b034c5eca8876caf78a3637cd07cd4a93873d7a/styles/prosilver/template/chat_buttons.html contenant l’include suivant : `<!-- INCLUDE posting_buttons.html -->` résolve le problème. L’auteur de ABBC3 recommande d’ailleurs son utilisation : https://www.phpbb.com/community/viewtopic.php?p=14123276#p14123276.

**Comment by Galixte** [comment]
Et avec ce commit aussi il a résolu le problème : https://github.com/LMOspaceace/ajaxchat/commit/3c5284f030490c0bb25d6f9dbe7ef6006e92f975.

**Comment by Galixte** [comment]
En attendant une investigation de ta part j’ai testé ta méthode mais 4 BBCodes ne s’affichent pas.
- 3 proviennent de ceux par défaut dans phpBB, il s’agit de QUOTE, URL et IMG.
- 1 provient de ABBC3, il s’agit de Flash `[flash=][/flash]`.

**Comment by ErnadoO** [comment]
Déjà, je ne pense pas que ce soit un problème avec posting_buttons.html, puisque contrairement à l'auteur d'Ajax Chat (à l'époque), j'ai toujours fais un include de posting_buttons.html dans la popup des commentaires.

Non le soucis comme je le dis sur .com, c'est l'inclusion de la css et du .js d'ABBC3 qui ne se fait pas puisque je n'utilise pas overall_header.html ni overall_footer.html

Après, il a la méthode crado utilisée par l'auteur d'Ajax Chat, consistant à dupliquer le code natif de phpBB pour apeler les events déstinés à overall_header.html alors qu'on utilise simple_header.html mais, désolé, je ne suis pas friand de ce genre de bidouille; la seule façon propre de faire étant celle que j'ai donné sur .com

Par contre effectivement il il y a un autre soucis quelque part car même si j'utilise overall_header/footer dans ma popup commentaire, j'ai les bbcode que tu cites qui disparaissent :/

Sherlock va donc investiguer ;)

**Comment by ErnadoO** [comment]
Alors ça c'est fort: si je désactive l'extension ABBC3, les bbcode capricieux ne réapparaissaient pas...

**Comment by ErnadoO** [comment]
Ok, capté, en fait ces 3 bbcode par défaut ne se sont jamais affichés dans la popup commentaire, à cause de ceci:

```
    <!-- IF S_BBCODE_IMG -->
        <input type="button" class="button2 bbcode-img" accesskey="p" name="addbbcode14" value="Img" style="width: 40px" onclick="bbstyle(14)" title="{L_BBCODE_P_HELP}" />
    <!-- ENDIF -->
    <!-- IF S_LINKS_ALLOWED -->
        <input type="button" class="button2 bbcode-url" accesskey="w" name="addbbcode16" value="URL" style="text-decoration: underline; width: 40px" onclick="bbstyle(16)" title="{L_BBCODE_W_HELP}" />
    <!-- ENDIF -->
    <!-- IF S_BBCODE_FLASH -->
        <input type="button" class="button2 bbcode-flash" accesskey="d" name="addbbcode18" value="Flash" onclick="bbstyle(18)" title="{L_BBCODE_D_HELP}" />
    <!-- ENDIF -->
```

Je n'ai jamais assigné ces variables conditionnelles, donc les bbcode correspondants ne peuvent s'afficher, logique... :D

**Comment by Galixte** [comment]
Cool au moins un bug de trouvé :p

**Comment by Galixte** [comment]
Et bien je garderais ta méthode alors, merci !-)

**Comment by Galixte** [comment]
Ah oui il manque QUOTE aussi.

**Comment by ErnadoO** [comment]
Le bbcode quote est également soumis à condition; il me suffit d'assigner ces variables côtés php pour afficher ces boutons; mais ça n'empêchera pas l'application du patch que j'ai donné sur .com pour la compatibilité avec ABBC3 hein :)

P.S: Laisse le ticket ouvert, tu le fermeras lorsque tu me confirmera que les bbcodes absents s'affichent bien dans le form d'ajout de site et dans la popup commentaire ;)

**Comment by Galixte** [comment]
Entendu.

**Comment by ErnadoO** [comment]
Ca devrait aller mieux ave ce dernier commit ;)

**Comment by Galixte** [comment]
Problème corrigé, merci. ;)
