### ISSUE TITLE
DIR_CREATE_CAT missing

### ISSUE THREAD

**Issue by David-NF** [ErnadoO/ext-phpbb-directory#22]
When I'm creating a new category, I see this: DIR_CREATE_CAT You see that in your tab/window in your browser thought that it was the Dutch translation but it looks like English has it as well.

**Comment by ErnadoO** [comment]
Hello

It's already fixed: https://github.com/ErnadoO/ext-phpbb-directory/commit/572d1a61bae5c891f82b296dbf65253f70055c3f

**Comment by David-NF** [comment]
Sorry about that, I looked at the closed issues but not in your commits. I was using the approved version setting it up as we speak. Congrats glad that is passed :) Thanks for all your work!

**Comment by ErnadoO** [comment]
Yeah i saw this bug yesterday so i didn't open an issue, i fixed that quickly.

You're welcome ;)
