### ISSUE TITLE
page blanche

### ISSUE THREAD

**Issue by hamidouki** [ErnadoO/ext-phpbb-directory#24]
bonjour
j'ai installé la derniere version de l'annuaire 1.0.0 , mais des que je me déconnecte de mon compte , je ne peut me connecter aprés , ni avec l'administrateur , ni avec un utilisateur 
j'ai une page blanche qui apparais
merci 
mon forum : www.bebwahran.com

**Comment by ErnadoO** [comment]
Bonjour

C'est normal, vu la capture d'écran postée sur ezcom-fr.com, je vois que tu utilises une langue qui n'est pas inclue dans mon extension (à savoir, la langue Arabe), et ton message d'erreur indique clairement le problème: Le fichier ext\ernadoo\phpbbdirectory\styles\prosilver\theme\ar\directory.css n'existe pas.
Je te conseilel donc de: 
1°) Désactiver l'extension
2°) Copier le dossier fr/ en ar/, afin d'avoir au final un fichier theme\ar\directory.css
3°) Réactiver l'extension

Je prépare un patch pour palier à ce soucis.

**Comment by hamidouki** [comment]
merci pour t'as réponse , je vien de traduire votre sujet https://translate.google.dz/translate?sl=en&tl=fr&js=y&prev=_t&hl=fr&ie=UTF-8&u=https%3A%2F%2Fwww.phpbb.com%2Fcommunity%2Fviewtopic.php%3Fp%3D14236441%23p14236441&edit-text=&act=url
et merci pour t'as réponse

**Comment by ErnadoO** [comment]
;)

**Comment by ErnadoO** [comment]
Pour info, le commit suivant règlera le problème: https://github.com/ErnadoO/ext-phpbb-directory/commit/958a91138b9df374eb2dc419d06cc7d5a2ee94c7
