### ISSUE TITLE
phpBB SEO

### ISSUE THREAD

**Issue by Skouat** [ErnadoO/ext-phpbb-directory#27]
Hi!

In your [lang file](https://github.com/ErnadoO/ext-phpbb-directory/blob/master/language/en/info_acp_directory.php#L53-L54) you specify that the rewriting is based on the DCZ's Ultimate SEO URL MOD.
For phpBB 3.1 and newer, MODs don't work. :-D
And, since a couple of days, http://www.phpbb-seo.com/ is down and the SEO extension abandonned.

**Comment by ErnadoO** [comment]
Good catch :p

Maybe be fix that in your pull request ? 😝

**Comment by Skouat** [comment]
From what I see, your extension doesn't use anymore these lang keys.
So, we only need to remove them?
And maybe remove the config `dir_activ_rewrite` installed by the v1.0.0 migration file?

**Comment by ErnadoO** [comment]
Yes we can remove language key but you're right, we need to remove sql entry too.

So i suggest à new PR for remove language key and add a migration file
