### ISSUE TITLE
Blank page on notification options page with phpBB 3.2.x

### ISSUE THREAD

**Issue by Galixte** [ErnadoO/ext-phpbb-directory#32]
Hi @ErnadoO,

could you take a look, please ? http://www.ezcom-fr.com/viewtopic.php?p=3275#p3275

**Comment by ErnadoO** [comment]
Hello

PhpBB Directory 1.0 **is not** compatible with phpBB 3.2

**Comment by Galixte** [comment]
Hi @ErnadoO, i know but he tryed to test the 2.0.x version but a message about the pre-requisites was displayed to him.

EDIT: okey, i see now: https://github.com/ErnadoO/ext-phpbb-directory/blob/3.2.x/composer.json#L23 phpBB 3.2.1… -_-

**Comment by ErnadoO** [comment]
Yes, because i use this feature: https://tracker.phpbb.com/browse/PHPBB3-14557 ;)
